#!/usr/bin/env python3
"""
Enhanced MCP Server with Peacock 4-Stage Integration - RESTORED ORIGINAL PROMPTS
"""
import http.server
import socketserver
import re
import json
import os
import urllib.request
import subprocess
import tempfile
import datetime

# --- CONFIGURATION ---
HOST = "127.0.0.1"
PORT = 8000
PROCESS_PATH = "/process"

# --- GROQ API CONFIGURATION - FIXED TO USE DEEPSEEK ---
GROQ_API_KEY = "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"
GROQ_MODEL_NAME = "deepseek-r1-distill-llama-70b"

# --- PEACOCK STAGE HANDLERS ---

class SparkHandler:
    """Requirements Analysis Stage"""
    
    def analyze_requirements(self, data):
        prompt = self._build_spark_prompt(data['text'])
        llm_response = call_llm(prompt)
        
        if llm_response.get("success"):
            return self._parse_spark_response(llm_response['text'])
        return {"error": "Spark analysis failed"}
    
    def _build_spark_prompt(self, project_idea):
        return f"""
Act as Spark, a strategic requirements analyst. Analyze this project idea and provide:

Project: {project_idea}

Provide analysis in this EXACT format:

**1. Core Objective:**
[One clear sentence describing the main goal]

**2. Current State:**
[Current situation/problems this solves]

**3. Target State:**
[Desired end state after implementation]

**4. In Scope:**
- [Feature 1]
- [Feature 2]
- [Feature 3]

**5. Out of Scope:**
- [What's NOT included]
- [Future considerations]

Keep it strategic and concise.
"""
    
    def _parse_spark_response(self, llm_text):
        return {
            "stage": "spark",
            "analysis_type": "requirements",
            "result_text": llm_text,
            "report_html": self._generate_spark_html(llm_text)
        }
    
    def _generate_spark_html(self, content):
        html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Peacock Spark - Requirements Analysis</title>
    <style>
        body {{ font-family: 'SF Pro Display', -apple-system, sans-serif; 
               max-width: 1200px; margin: 0 auto; padding: 40px 20px; 
               background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
               color: #333; }}
        .container {{ background: white; border-radius: 20px; 
                     padding: 40px; box-shadow: 0 20px 60px rgba(0,0,0,0.1); }}
        h1 {{ color: #2d3748; border-bottom: 3px solid #667eea; padding-bottom: 15px; }}
        .stage-badge {{ background: #667eea; color: white; padding: 8px 16px; 
                       border-radius: 20px; font-weight: bold; display: inline-block; 
                       margin-bottom: 20px; }}
        pre {{ background: #f7fafc; padding: 20px; border-radius: 10px; 
               border-left: 4px solid #667eea; overflow-x: auto; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="stage-badge">🦚 STAGE 1: SPARK</div>
        <h1>Requirements Analysis</h1>
        <pre>{content}</pre>
        <p><em>Generated by Peacock Spark at {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</em></p>
    </div>
</body>
</html>
"""
        return self._save_html_report("spark", html_content)


class FalconHandler:
    """Architecture Design Stage"""
    
    def design_architecture(self, data):
        prompt = self._build_falcon_prompt(data['text'])
        llm_response = call_llm(prompt)
        
        if llm_response.get("success"):
            return self._parse_falcon_response(llm_response['text'])
        return {"error": "Falcon architecture design failed"}
    
    def _build_falcon_prompt(self, project_requirements):
        return f"""
Act as Falcon, a solution architect. Design the technical architecture for this project:

Requirements: {project_requirements}

Provide architecture in this EXACT format:

**1. Technology Stack:**
- Frontend: [Specific framework/library]
- Backend: [Specific framework/language]
- Database: [Specific database choice]
- APIs: [External services]
- Deployment: [Cloud/hosting strategy]

**2. Architecture Pattern:**
[Describe the overall pattern - monolithic, microservices, etc.]

**3. File Structure:**
```
project-name/
├── frontend/
├── backend/
├── database/
└── docs/
```

**4. Data Flow:**
[Describe how data moves through the system]

**5. Key Implementation Decisions:**
- [Decision 1 with rationale]
- [Decision 2 with rationale]

Be specific with technologies and justify choices.
"""
    
    def _parse_falcon_response(self, llm_text):
        return {
            "stage": "falcon",
            "analysis_type": "architecture",
            "result_text": llm_text,
            "report_html": self._generate_falcon_html(llm_text)
        }
    
    def _generate_falcon_html(self, content):
        html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Peacock Falcon - Architecture Design</title>
    <style>
        body {{ font-family: 'SF Pro Display', -apple-system, sans-serif; 
               max-width: 1200px; margin: 0 auto; padding: 40px 20px; 
               background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
               color: #333; }}
        .container {{ background: white; border-radius: 20px; 
                     padding: 40px; box-shadow: 0 20px 60px rgba(0,0,0,0.1); }}
        h1 {{ color: #2d3748; border-bottom: 3px solid #f093fb; padding-bottom: 15px; }}
        .stage-badge {{ background: #f093fb; color: white; padding: 8px 16px; 
                       border-radius: 20px; font-weight: bold; display: inline-block; 
                       margin-bottom: 20px; }}
        pre {{ background: #f7fafc; padding: 20px; border-radius: 10px; 
               border-left: 4px solid #f093fb; overflow-x: auto; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="stage-badge">🦅 STAGE 2: FALCON</div>
        <h1>Architecture Design</h1>
        <pre>{content}</pre>
        <p><em>Generated by Peacock Falcon at {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</em></p>
    </div>
</body>
</html>
"""
        return self._save_html_report("falcon", html_content)


class EagleHandler:
    """Implementation Stage"""
    
    def generate_implementation(self, data):
        prompt = self._build_eagle_prompt(data['text'])
        llm_response = call_llm(prompt)
        
        if llm_response.get("success"):
            return self._parse_eagle_response(llm_response['text'])
        return {"error": "Eagle implementation failed"}
    
    def _build_eagle_prompt(self, architecture_design):
        return f"""
Act as Eagle, an implementation specialist. Create executable setup and code for this architecture:

Architecture: {architecture_design}

Provide implementation in this EXACT format:

**1. Setup Commands:**
```bash
# Complete setup commands here
npm init -y
npm install express react
# etc...
```

**2. Directory Structure:**
```
project/
├── src/
│   ├── components/
│   └── utils/
├── public/
└── package.json
```

**3. Key Files to Create:**
**server.js:**
```javascript
// Complete working server code
```

**App.js:**
```javascript
// Complete working frontend code
```

**4. Initial Code Scaffolding:**
[Provide minimal working code for each component]

**5. First Working Prototype Steps:**
1. Run setup commands
2. Start development server
3. Test basic functionality
4. Verify all components work

Make it executable and ready to run immediately.
"""
    
    def _parse_eagle_response(self, llm_text):
        return {
            "stage": "eagle",
            "analysis_type": "implementation",
            "result_text": llm_text,
            "report_html": self._generate_eagle_html(llm_text)
        }
    
    def _generate_eagle_html(self, content):
        html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Peacock Eagle - Implementation Guide</title>
    <style>
        body {{ font-family: 'SF Pro Display', -apple-system, sans-serif; 
               max-width: 1200px; margin: 0 auto; padding: 40px 20px; 
               background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
               color: #333; }}
        .container {{ background: white; border-radius: 20px; 
                     padding: 40px; box-shadow: 0 20px 60px rgba(0,0,0,0.1); }}
        h1 {{ color: #2d3748; border-bottom: 3px solid #4facfe; padding-bottom: 15px; }}
        .stage-badge {{ background: #4facfe; color: white; padding: 8px 16px; 
                       border-radius: 20px; font-weight: bold; display: inline-block; 
                       margin-bottom: 20px; }}
        pre {{ background: #f7fafc; padding: 20px; border-radius: 10px; 
               border-left: 4px solid #4facfe; overflow-x: auto; }}
        code {{ background: #e2e8f0; padding: 2px 6px; border-radius: 4px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="stage-badge">🦅 STAGE 3: EAGLE</div>
        <h1>Implementation Guide</h1>
        <pre>{content}</pre>
        <p><em>Generated by Peacock Eagle at {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</em></p>
    </div>
</body>
</html>
"""
        return self._save_html_report("eagle", html_content)


class HawkHandler:
    """Quality Assurance Stage"""
    
    def analyze_quality(self, data):
        prompt = self._build_hawk_prompt(data['text'])
        llm_response = call_llm(prompt)
        
        if llm_response.get("success"):
            return self._parse_hawk_response(llm_response['text'])
        return {"error": "Hawk QA analysis failed"}
    
    def _build_hawk_prompt(self, implementation_details):
        return f"""
Act as Hawk, a quality assurance specialist. Create comprehensive QA strategy for this implementation:

Implementation: {implementation_details}

Provide QA strategy in this EXACT format:

**1. Test Cases:**
- Functional tests for core features
- Edge cases and error scenarios
- Integration test requirements

**2. Security Validation:**
- Authentication/authorization checks
- Input validation requirements
- Data protection measures

**3. Performance Considerations:**
- Load testing requirements
- Scalability checkpoints
- Resource optimization

**4. Error Handling Scenarios:**
- Network failure handling
- Data corruption recovery
- User error management

**5. Production Readiness Checklist:**
- Deployment requirements
- Monitoring setup
- Backup strategies
- Compliance checks

Be specific and actionable for each area.
"""
    
    def _parse_hawk_response(self, llm_text):
        return {
            "stage": "hawk", 
            "analysis_type": "quality_assurance",
            "result_text": llm_text,
            "report_html": self._generate_hawk_html(llm_text)
        }
    
    def _generate_hawk_html(self, content):
        html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Peacock Hawk - Quality Assurance</title>
    <style>
        body {{ font-family: 'SF Pro Display', -apple-system, sans-serif; 
               max-width: 1200px; margin: 0 auto; padding: 40px 20px; 
               background: linear-gradient(135deg, #fa709a 0%, #fee140 100%);
               color: #333; }}
        .container {{ background: white; border-radius: 20px; 
                     padding: 40px; box-shadow: 0 20px 60px rgba(0,0,0,0.1); }}
        h1 {{ color: #2d3748; border-bottom: 3px solid #fa709a; padding-bottom: 15px; }}
        .stage-badge {{ background: #fa709a; color: white; padding: 8px 16px; 
                       border-radius: 20px; font-weight: bold; display: inline-block; 
                       margin-bottom: 20px; }}
        pre {{ background: #f7fafc; padding: 20px; border-radius: 10px; 
               border-left: 4px solid #fa709a; overflow-x: auto; }}
        .checklist {{ background: #f0fff4; padding: 15px; border-radius: 8px; 
                     border-left: 4px solid #38a169; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="stage-badge">🦅 STAGE 4: HAWK</div>
        <h1>Quality Assurance Strategy</h1>
        <pre>{content}</pre>
        <p><em>Generated by Peacock Hawk at {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</em></p>
    </div>
</body>
</html>
"""
        return self._save_html_report("hawk", html_content)


# Shared HTML report saving method
def _save_html_report(stage_name, html_content):
    """Save HTML report and return filepath"""
    reports_dir = os.path.expanduser("~/peacock_reports")
    os.makedirs(reports_dir, exist_ok=True)
    
    timestamp = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"peacock_{stage_name}_{timestamp}.html"
    filepath = os.path.join(reports_dir, filename)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    return filepath


# Initialize stage handlers
spark_handler = SparkHandler()
falcon_handler = FalconHandler()
eagle_handler = EagleHandler()
hawk_handler = HawkHandler()


# --- ENHANCED LLM FUNCTIONS ---

def build_llm_prompt(command, text, language):
    """Builds prompts for both traditional and Peacock stage commands"""
    
    # Peacock stage commands
    if command == "spark_analysis":
        return spark_handler._build_spark_prompt(text)
    elif command == "falcon_architecture":
        return falcon_handler._build_falcon_prompt(text)
    elif command == "eagle_implementation":
        return eagle_handler._build_eagle_prompt(text)
    elif command == "hawk_qa":
        return hawk_handler._build_hawk_prompt(text)
    elif command == "peacock_full":
        # Full analysis with interface generation
        return f"""
You are LLM2 - expert code generator for Peacock.

Generate COMPLETE, WORKING code for this project:
{text}

Requirements:
1. Make it ACTUALLY functional and ready to run
2. Include ALL necessary files
3. Add proper error handling
4. Use modern best practices

Format each file as:
```filename: path/to/file.ext
[complete file content here]
```

Generate a complete implementation now:
"""
    elif command == "fix_xedit_paths":
        xedit_paths = text if isinstance(text, list) else []
        return f"""
Fix and improve the code at these XEdit-Paths: {', '.join(xedit_paths)}

Provide the corrected code with explanations for each fix.
Focus on:
1. Bug fixes
2. Performance improvements  
3. Code quality enhancements
4. Best practices

Return the improved code ready to use.
"""
    
    # Traditional code analysis commands
    elif command == "explain":
        return f"Explain the following {language} code:\n\n{text}\n\nProvide a clear, concise explanation."
    elif command == "fix":
        return f"Review and fix this {language} code. Provide corrected version and explanation:\n\n{text}"
    elif command == "rewrite":
        return f"Rewrite this {language} code to be more efficient/idiomatic:\n\n{text}"
    elif command == "alternatives":
        return f"Suggest alternative approaches for this {language} code:\n\n{text}"
    elif command == "question":
        return f"Analyze this {language} code and provide insights:\n\n{text}"
    else:
        return f"Analyze the following {language} code:\n\n{text}"


def extract_code_from_llm(llm_response):
    """Extract code from LLM response - FIXED for DeepSeek"""
    import re
    
    print(f"🔍 DEBUG: extract_code_from_llm called")
    print(f"   Response length: {len(llm_response)} chars")
    print(f"   First 300 chars: {llm_response[:300]}...")
    
    # Look for code blocks with various patterns
    patterns = [
        r"```(?:filename:\s*)?[^\n]*\n(.*?)```",  # Original pattern
        r"```python\n(.*?)```",                   # Python specific
        r"```\n(.*?)```",                         # Simple pattern
    ]
    
    for i, pattern in enumerate(patterns):
        matches = re.findall(pattern, llm_response, re.DOTALL)
        print(f"   Pattern {i+1} found {len(matches)} matches")
        if matches:
            # Take ALL matches, not just first one
            all_code = "\n\n".join(matches)
            print(f"   Using combined matches: {len(all_code)} chars")
            return all_code
    
    print("   ❌ NO CODE BLOCKS FOUND! Using full response")
    # Return the whole response if nothing else works
    return llm_response


def generate_interfaces_for_project(code_content, project_name):
    """Generate XEdit and Model Dashboard interfaces"""
    try:
        import sys
        from pathlib import Path
        import webbrowser
        import shutil
        
        # Add generators to path
        generators_path = Path(__file__).parent.parent / "generators"
        if str(generators_path) not in sys.path:
            sys.path.append(str(generators_path))
        
        from mockup_xedit_generator import generate_enhanced_html_interface
        from peacock_model_dashboard import generate_model_dashboard
        
        # Create directories
        reports_dir = Path(__file__).parent.parent / "html" / "reports"
        reports_dir.mkdir(parents=True, exist_ok=True)
        
        # Generate XEdit interface
        xedit_path = generate_enhanced_html_interface(code_content, project_name, 3)
        xedit_reports_path = reports_dir / "peacock_xedit_interface.html"
        
        if str(xedit_path) != str(xedit_reports_path):
            shutil.copy2(xedit_path, xedit_reports_path)
        
        # Generate Model Dashboard
        dashboard_path = generate_model_dashboard()
        dashboard_reports_path = reports_dir / "peacock_model_dashboard.html"
        
        if str(dashboard_path) != str(dashboard_reports_path):
            shutil.copy2(dashboard_path, dashboard_reports_path)
        
        # Auto-open interfaces
        webbrowser.open(f"file://{xedit_reports_path.absolute()}")
        webbrowser.open(f"file://{dashboard_reports_path.absolute()}")
        
        print(f"🌐 Opened XEdit interface: {xedit_reports_path}")
        print(f"🌐 Opened Model Dashboard: {dashboard_reports_path}")
        
        return str(xedit_reports_path), str(dashboard_reports_path)
    except Exception as e:
        print(f"Interface generation failed: {e}")
        return None, None


def call_llm(prompt):
    """Calls Groq API and saves everything to debug files"""
    import os
    from datetime import datetime
    
    # Create debug directory
    debug_dir = "/home/flintx/peacock/debug_logs"
    os.makedirs(debug_dir, exist_ok=True)
    
    # Save the prompt being sent
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    prompt_file = f"{debug_dir}/prompt_{timestamp}.txt"
    with open(prompt_file, "w") as f:
        f.write("="*80 + "\n")
        f.write("PROMPT SENT TO GROQ:\n")
        f.write("="*80 + "\n")
        f.write(f"Model: {GROQ_MODEL_NAME}\n")
        f.write(f"Timestamp: {datetime.now()}\n")
        f.write("="*80 + "\n")
        f.write(prompt)
        f.write("\n" + "="*80)
    
    print(f"💾 SAVED PROMPT TO: {prompt_file}")
    
    try:
        from groq import Groq
        client = Groq(api_key=GROQ_API_KEY)
        chat_completion = client.chat.completions.create(
            messages=[{"role": "user", "content": prompt}],
            model=GROQ_MODEL_NAME,
            temperature=0.1
        )
        
        response_text = chat_completion.choices[0].message.content
        
        # Save the full response
        response_file = f"{debug_dir}/response_{timestamp}.txt"
        with open(response_file, "w") as f:
            f.write("="*80 + "\n")
            f.write("FULL RESPONSE FROM GROQ:\n")
            f.write("="*80 + "\n")
            f.write(f"Model: {GROQ_MODEL_NAME}\n")
            f.write(f"Response Length: {len(response_text)} chars\n")
            f.write(f"Timestamp: {datetime.now()}\n")
            f.write("="*80 + "\n")
            f.write(response_text)
            f.write("\n" + "="*80)
        
        print(f"💾 SAVED RESPONSE TO: {response_file}")
        print(f"📊 RESPONSE LENGTH: {len(response_text)} chars")
        
        # Save extracted code separately
        import re
        code_blocks = re.findall(r"```(?:filename:\s*)?[^\n]*\n(.*?)```", response_text, re.DOTALL)
        if code_blocks:
            code_file = f"{debug_dir}/extracted_code_{timestamp}.txt"
            with open(code_file, "w") as f:
                f.write("="*80 + "\n")
                f.write(f"EXTRACTED CODE BLOCKS ({len(code_blocks)} found):\n")
                f.write("="*80 + "\n")
                for i, block in enumerate(code_blocks, 1):
                    f.write(f"\n--- CODE BLOCK {i} ---\n")
                    f.write(block)
                    f.write(f"\n--- END BLOCK {i} ---\n")
            print(f"💾 SAVED EXTRACTED CODE TO: {code_file}")
        
        return {"success": True, "text": response_text}
        
    except Exception as e:
        error_file = f"{debug_dir}/error_{timestamp}.txt"
        with open(error_file, "w") as f:
            f.write(f"ERROR: {e}\n")
            f.write(f"Model: {GROQ_MODEL_NAME}\n")
            f.write(f"Timestamp: {datetime.now()}\n")
        print(f"💾 SAVED ERROR TO: {error_file}")
        return {"error": f"Groq API call failed: {e}"}


def process_llm_response(command, llm_raw_text, location_info, original_request=None):
    """Enhanced IRP with Peacock stage routing and fresh code generation"""
    
    # Route Peacock stage commands to appropriate handlers
    if command == "spark_analysis":
        return spark_handler._parse_spark_response(llm_raw_text)
    elif command == "falcon_architecture":
        return falcon_handler._parse_falcon_response(llm_raw_text)
    elif command == "eagle_implementation":
        return eagle_handler._parse_eagle_response(llm_raw_text)
    elif command == "hawk_qa":
        return hawk_handler._parse_hawk_response(llm_raw_text)
    elif command == "peacock_full":
        # Full analysis with interface generation
        try:
            # Extract fresh code from LLM response
            fresh_code = extract_code_from_llm(llm_raw_text)
            project_name = "Generated Project"
            
            # Generate interfaces
            xedit_path, dashboard_path = generate_interfaces_for_project(fresh_code, project_name)
            
            # Create comprehensive report - FIXED HTML TEMPLATE
            html_content = """
<!DOCTYPE html>
<html>
<head>
    <title>Peacock Complete Analysis</title>
    <style>
        body { font-family: 'SF Pro Display', -apple-system, sans-serif; 
               max-width: 1200px; margin: 0 auto; padding: 40px 20px; 
               background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
               color: #333; }
        .container { background: white; border-radius: 20px; 
                     padding: 40px; box-shadow: 0 20px 60px rgba(0,0,0,0.1); }
        h1 { color: #2d3748; border-bottom: 3px solid #667eea; padding-bottom: 15px; }
        .full-badge { background: linear-gradient(135deg, #667eea, #764ba2); 
                      color: white; padding: 12px 24px; border-radius: 25px; 
                      font-weight: bold; display: inline-block; margin-bottom: 30px;
                      font-size: 18px; }
        pre { background: #f7fafc; padding: 20px; border-radius: 10px; 
               border-left: 4px solid #667eea; overflow-x: auto; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Peacock Analysis Report</h1>
        <div class="full-badge">Complete Analysis</div>
        <div class="content">
            <pre>""" + llm_raw_text + """</pre>
        </div>
    </div>
</body>
</html>
"""
            return {
                "analysis_type": "peacock_fresh_interface",
                "result_text": llm_raw_text,
                "xedit_html": xedit_path,
                "dashboard_html": dashboard_path,
                "report_html": _save_html_report("complete", html_content),
                "file_count": len(re.findall(r'```filename:', llm_raw_text)),
                "pipeline_stages": {
                    "fresh_code_generation": "✅ Complete",
                    "interface_generation": "✅ Complete", 
                    "model_dashboard_generation": "✅ Complete"
                }
            }
        except Exception as e:
            print(f"❌ ERROR in peacock_full: {e}")
            # Fallback to basic report
            html_content = """
<!DOCTYPE html>
<html>
<head>
    <title>Peacock Complete Analysis</title>
    <style>
        body { font-family: 'SF Pro Display', -apple-system, sans-serif; 
               max-width: 1200px; margin: 0 auto; padding: 40px 20px; 
               background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
               color: #333; }
        .container { background: white; border-radius: 20px; 
                     padding: 40px; box-shadow: 0 20px 60px rgba(0,0,0,0.1); }
        h1 { color: #2d3748; border-bottom: 3px solid #667eea; padding-bottom: 15px; }
        .full-badge { background: linear-gradient(135deg, #667eea, #764ba2); 
                      color: white; padding: 12px 24px; border-radius: 25px; 
                      font-weight: bold; display: inline-block; margin-bottom: 30px;
                      font-size: 18px; }
        pre { background: #f7fafc; padding: 20px; border-radius: 10px; 
               border-left: 4px solid #667eea; overflow-x: auto; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Peacock Analysis Report</h1>
        <div class="full-badge">Complete Analysis</div>
        <div class="content">
            <pre>""" + llm_raw_text + """</pre>
        </div>
    </div>
</body>
</html>
"""
            return {
                "analysis_type": "complete",
                "result_text": llm_raw_text,
                "report_html": _save_html_report("complete", html_content),
                "error": str(e)
            }
    
    # Traditional code commands (existing logic)
    internal_data = {}
    
    if command in ["explain", "question"]:
        internal_data["explanation_text"] = llm_raw_text
        internal_data["result_text"] = llm_raw_text
    elif command in ["fix", "rewrite"]:
        # Parse code fixes
        suggested_change = {
            "type": "replace",
            "replacement_code": "Could not parse suggested code from LLM.",
            "explanation": "Could not parse explanation from LLM.",
            "start_line_1based": location_info.get('selected_region', {}).get('start', {}).get('line_1based', '??'),
            "end_line_1based": location_info.get('selected_region', {}).get('end', {}).get('line_1based', '??')
        }
        
        # Simple code block extraction
        lines = llm_raw_text.splitlines()
        code_blocks = []
        in_code_block = False
        current_code_block = []
        
        for line in lines:
            if line.strip().startswith("```"):
                if in_code_block:
                    code_blocks.append("\n".join(current_code_block))
                    current_code_block = []
                    in_code_block = False
                else:
                    in_code_block = True
            elif in_code_block:
                current_code_block.append(line)
        
        if code_blocks:
            suggested_change["replacement_code"] = code_blocks[-1].strip()
        
        internal_data["suggested_change"] = suggested_change
    else:
        internal_data["result_text"] = llm_raw_text
    
    internal_data["_raw_llm_response"] = llm_raw_text
    return internal_data


# --- ENHANCED REQUEST HANDLER ---

class EnhancedMCPRequestHandler(http.server.BaseHTTPRequestHandler):
    def log_request(self, code='-', size='-'):
        pass

    def do_OPTIONS(self):
        """Handle CORS preflight requests"""
        self.send_response(200)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "POST, GET, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_GET(self):
        """Handle GET requests for health checks"""
        if self.path == "/health":
            self.send_response(200)
            self.send_header("Content-type", "application/json")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            health_data = {
                "status": "healthy", 
                "model": GROQ_MODEL_NAME,
                "api": "groq"
            }
            self.wfile.write(json.dumps(health_data).encode("utf-8"))
        else:
            self.send_response(404)
            self.end_headers()

    def do_POST(self):
        if self.path == PROCESS_PATH:
            content_length = int(self.headers['Content-Length'])
            post_data = self.rfile.read(content_length)

            try:
                received_data = json.loads(post_data.decode('utf-8'))
                
                command = received_data.get('command', 'unknown')
                text_to_process = received_data.get('text', '')
                language = received_data.get('language', 'unknown')
                location_info = received_data.get('location', {})
                original_request = received_data.get('original_request', received_data.get('project_request'))

                # DEBUG OUTPUT
                print("🔍 DEBUG: Full payload received:")
                print(f"   Command: {command}")
                print(f"   Text: {text_to_process[:100] if text_to_process else 'None'}...")
                print(f"   Language: {language}")
                print(f"   Original Request: {original_request}")
                print("=" * 50)

                # Handle XEdit-specific commands
                if command == "fix_xedit_paths":
                    xedit_paths = received_data.get('xedit_paths', [])
                    print(f"🎯 Processing XEdit paths: {xedit_paths}")
                    text_to_process = xedit_paths

                print("Enhanced MCP: Received data from EIP:")
                print("---")
                print("Command: {}".format(command))
                print("Language: {}".format(language))
                print("File: {}".format(os.path.basename(location_info.get('filepath', 'N/A'))))
                if original_request:
                    print("Original Request: {}".format(original_request[:50]))
                print("---")

                # Build prompt and call LLM
                llm_prompt = build_llm_prompt(command, text_to_process, language)
                
                print(f"🔍 DEBUG: Sending prompt to Groq:")
                print(f"   Prompt length: {len(llm_prompt)} chars")
                print(f"   First 200 chars: {llm_prompt[:200]}...")
                print("=" * 50)
                
                llm_response = call_llm(llm_prompt)

                # DEBUG GROQ RESPONSE
                print(f"🔍 DEBUG: Groq API Response:")
                print(f"   Success: {llm_response.get('success')}")
                if llm_response.get("success"):
                    response_text = llm_response.get("text", "")
                    print(f"   Response length: {len(response_text)} chars")
                    print(f"   First 200 chars: {response_text[:200]}...")
                    print(f"🔍 DEBUG: Looking for code blocks...")
                    import re
                    code_blocks = re.findall(r"```(?:filename:\s*)?[^\n]*\n(.*?)```", response_text, re.DOTALL)
                    print(f"   Found {len(code_blocks)} code blocks")
                    if code_blocks:
                        print(f"   First code block length: {len(code_blocks[0])} chars")
                        print(f"   First code block preview: {code_blocks[0][:100]}...")
                    else:
                        print("   NO CODE BLOCKS FOUND! Response format might be wrong")
                else:
                    print(f"   Error: {llm_response.get('error')}")
                print("=" * 50)

                if llm_response.get("success"):
                    llm_raw_text = llm_response.get("text", "")
                    internal_structured_data = process_llm_response(command, llm_raw_text, location_info, original_request)

                    # DEBUG MCP PROCESSING
                    print(f"🔍 DEBUG: MCP Processing Result:")
                    print(f"   Analysis type: {internal_structured_data.get('analysis_type')}")
                    print(f"   Has xedit_html: {'xedit_html' in internal_structured_data}")
                    print(f"   Has dashboard_html: {'dashboard_html' in internal_structured_data}")
                    if "error" in internal_structured_data:
                        print(f"   ERROR: {internal_structured_data['error']}")
                    print("=" * 50)

                    # Prepare response
                    response_payload = {
                        "status": "success",
                        "command": command,
                        "message": "Enhanced MCP processed successfully.",
                        "internal_data": internal_structured_data,
                        "location": location_info
                    }
                    
                    # Add report filepath if generated
                    if "report_html" in internal_structured_data:
                        response_payload["report_filepath"] = internal_structured_data["report_html"]
                    if "xedit_html" in internal_structured_data:
                        response_payload["report_filepath"] = internal_structured_data["xedit_html"]

                    self.send_response(200)
                    self.send_header('Content-type', 'application/json')
                    self.send_header("Access-Control-Allow-Origin", "*")
                    self.end_headers()
                    self.wfile.write(json.dumps(response_payload).encode('utf-8'))

                else:
                    error_message = llm_response.get("error", "Unknown LLM error.")
                    print(f"❌ LLM ERROR: {error_message}")
                    self.send_response(500)
                    self.send_header('Content-type', 'application/json')
                    self.send_header("Access-Control-Allow-Origin", "*")
                    self.end_headers()
                    error_payload = {
                        "status": "error",
                        "command": command,
                        "message": f"Enhanced MCP: LLM processing failed: {error_message}",
                        "internal_data": {"_llm_error": error_message}
                    }
                    self.wfile.write(json.dumps(error_payload).encode('utf-8'))

            except Exception as e:
                print(f"❌ EXCEPTION: {e}")
                import traceback
                traceback.print_exc()
                self.send_response(500)
                self.send_header('Content-type', 'application/json')
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                error_payload = {
                    "status": "error",
                    "message": "Enhanced MCP: Processing error: {}".format(e),
                    "command": "internal_error"
                }
                self.wfile.write(json.dumps(error_payload).encode('utf-8'))
        else:
            self.send_response(404)
            self.end_headers()
            self.wfile.write(b'404 Not Found')


# --- SERVER STARTUP ---
if __name__ == "__main__":
    with socketserver.TCPServer((HOST, PORT), EnhancedMCPRequestHandler, bind_and_activate=False) as httpd:
        httpd.allow_reuse_address = True
        httpd.server_bind()
        httpd.server_activate()

        print("Enhanced MCP: Starting Peacock server on {}:{}".format(HOST, PORT))
        print("Enhanced MCP: Peacock stages ready - Spark/Falcon/Eagle/Hawk")
        print("Enhanced MCP: Using Groq API with {}".format(GROQ_MODEL_NAME))
        print("Enhanced MCP: Press Ctrl+C to stop.")

        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nEnhanced MCP: Stopping Peacock server.")
            httpd.shutdown()
            print("Enhanced MCP: Peacock server stopped.")