def extract_code_from_llm(llm_response):
    """Extract the first code block from LLM response for interface generation"""
    import re
    
    print(f"🔍 DEBUG: extract_code_from_llm called")
    print(f"   Response length: {len(llm_response)} chars")
    print(f"   First 300 chars: {llm_response[:300]}...")
    
    # Look for code blocks with various patterns
    patterns = [
        r'```(?:filename:\s*)?[^\n]*\n(.*?)```',  # Original pattern
        r'```python\n(.*?)```',                   # Python specific
        r'```\n(.*?)```',                         # Simple pattern
    ]
    
    for i, pattern in enumerate(patterns):
        matches = re.findall(pattern, llm_response, re.DOTALL)
        print(f"   Pattern {i+1} found {len(matches)} matches")
        if matches:
            code = matches[0].strip()
            print(f"   Using match: {len(code)} chars")
            print(f"   Code preview: {code[:100]}...")
            return code
    
    print("   ❌ NO CODE BLOCKS FOUND! Using fallback")
    # Fallback - return sample code if no blocks found
    return '''def main():
    print("Generated by Peacock!")
    calculator = Calculator()
    calculator.run()

class Calculator:
    def __init__(self):
        self.result = 0
    
    def run(self):
        print("Calculator started")
        # Add your logic here
'''
