#!/usr/bin/env python3
"""
Peacock Download Manager - Package generated code into downloadable zip files
"""

import zipfile
import json
import re
import os
import tempfile
import shutil
from pathlib import Path
from datetime import datetime

class PeacockDownloadManager:
    def __init__(self):
        self.temp_dir = Path(tempfile.gettempdir()) / "peacock_downloads"
        self.temp_dir.mkdir(exist_ok=True)
        
    def extract_files_from_llm_response(self, llm_response):
        """Extract code files from LLM response"""
        files = []
        
        # Pattern to match filename blocks
        file_pattern = r'```(?:filename:\s*)?([^\n]+\.[a-zA-Z0-9]+)\n(.*?)```'
        matches = re.findall(file_pattern, llm_response, re.DOTALL)
        
        for filename, content in matches:
            # Clean filename
            filename = filename.strip()
            if filename.startswith('filename:'):
                filename = filename.replace('filename:', '').strip()
            
            files.append({
                "name": filename,
                "content": content.strip(),
                "language": self._detect_language(filename)
            })
        
        return files
    
    def _detect_language(self, filename):
        """Detect programming language from filename"""
        ext_map = {
            '.py': 'python',
            '.js': 'javascript', 
            '.html': 'html',
            '.css': 'css',
            '.json': 'json',
            '.md': 'markdown',
            '.sh': 'bash',
            '.rs': 'rust',
            '.go': 'go',
            '.java': 'java',
            '.cpp': 'cpp',
            '.c': 'c',
            '.ts': 'typescript',
            '.jsx': 'jsx',
            '.tsx': 'tsx',
            '.vue': 'vue',
            '.php': 'php',
            '.rb': 'ruby',
            '.yml': 'yaml',
            '.yaml': 'yaml',
            '.toml': 'toml',
            '.ini': 'ini',
            '.cfg': 'config',
            '.txt': 'text'
        }
        
        ext = Path(filename).suffix.lower()
        return ext_map.get(ext, 'text')
    
    def generate_setup_script(self, files, project_name):
        """Generate setup script based on detected languages"""
        languages = set(file['language'] for file in files)
        
        # Detect main language and framework
        main_language = self._detect_main_language(files)
        framework = self._detect_framework(files)
        
        script_content = f"""#!/bin/bash
# {project_name} - Auto-generated setup script
# Generated by Peacock on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

echo "🦚 Setting up {project_name}..."
echo "Detected: {main_language.title()}"
"""
        
        if framework:
            script_content += f'echo "Framework: {framework}"\n'
        
        script_content += "\n"
        
        # Add language-specific setup
        if 'python' in languages:
            script_content += self._generate_python_setup(files)
        elif 'javascript' in languages or 'typescript' in languages:
            script_content += self._generate_node_setup(files)
        elif 'rust' in languages:
            script_content += self._generate_rust_setup(files)
        elif 'go' in languages:
            script_content += self._generate_go_setup(files)
        else:
            script_content += self._generate_generic_setup(files)
        
        # Add run instructions
        script_content += self._generate_run_instructions(files, main_language)
        
        return script_content
    
    def _detect_main_language(self, files):
        """Detect the main programming language"""
        language_count = {}
        for file in files:
            lang = file['language']
            if lang not in ['text', 'markdown', 'json']:
                language_count[lang] = language_count.get(lang, 0) + 1
        
        if language_count:
            return max(language_count, key=language_count.get)
        return 'text'
    
    def _detect_framework(self, files):
        """Detect framework from file contents"""
        all_content = ' '.join(file['content'] for file in files)
        
        frameworks = {
            'pygame': ['import pygame', 'pygame.'],
            'flask': ['from flask', 'Flask('],
            'django': ['from django', 'django.'],
            'react': ['import React', 'from react'],
            'vue': ['Vue.', '<template>'],
            'express': ['express()', 'require("express")'],
            'fastapi': ['from fastapi', 'FastAPI('],
            'tkinter': ['import tkinter', 'from tkinter'],
            'qt': ['PyQt', 'PySide'],
            'kivy': ['from kivy', 'import kivy']
        }
        
        for framework, patterns in frameworks.items():
            if any(pattern in all_content for pattern in patterns):
                return framework
        
        return None
    
    def _generate_python_setup(self, files):
        """Generate Python-specific setup"""
        setup = """# Python Setup
if ! command -v python3 &> /dev/null; then
    echo "❌ Python 3 not found. Please install Python 3.8+"
    exit 1
fi

echo "✅ Python 3 found"

# Check for requirements.txt or detect dependencies
"""
        
        # Check if requirements.txt exists
        has_requirements = any(file['name'] == 'requirements.txt' for file in files)
        
        if has_requirements:
            setup += """if [ -f "requirements.txt" ]; then
    echo "📦 Installing dependencies from requirements.txt..."
    python3 -m pip install -r requirements.txt
fi
"""
        else:
            # Auto-detect common imports
            all_content = ' '.join(file['content'] for file in files)
            dependencies = []
            
            common_packages = {
                'pygame': 'pygame',
                'flask': 'flask',
                'django': 'django',
                'fastapi': 'fastapi',
                'requests': 'requests',
                'numpy': 'numpy',
                'pandas': 'pandas',
                'matplotlib': 'matplotlib',
                'tkinter': '',  # Built-in
                'sqlite3': '',  # Built-in
                'json': '',     # Built-in
                'os': '',       # Built-in
                'sys': '',      # Built-in
                'random': '',   # Built-in
                'time': '',     # Built-in
                'datetime': '', # Built-in
                'pathlib': '',  # Built-in
                'typing': '',   # Built-in
            }
            
            for package, pip_name in common_packages.items():
                if f'import {package}' in all_content or f'from {package}' in all_content:
                    if pip_name:  # Only add if it needs pip install
                        dependencies.append(pip_name)
            
            if dependencies:
                setup += f"""echo "📦 Installing detected dependencies..."
python3 -m pip install {' '.join(dependencies)}
"""
        
        return setup + "\n"
    
    def _generate_node_setup(self, files):
        """Generate Node.js setup"""
        setup = """# Node.js Setup
if ! command -v node &> /dev/null; then
    echo "❌ Node.js not found. Please install Node.js 16+"
    exit 1
fi

echo "✅ Node.js found"

# Check for package.json
"""
        
        has_package_json = any(file['name'] == 'package.json' for file in files)
        
        if has_package_json:
            setup += """if [ -f "package.json" ]; then
    echo "📦 Installing dependencies..."
    npm install
fi
"""
        else:
            setup += """echo "📦 Initializing npm project..."
npm init -y
"""
        
        return setup + "\n"
    
    def _generate_rust_setup(self, files):
        """Generate Rust setup"""
        return """# Rust Setup
if ! command -v cargo &> /dev/null; then
    echo "❌ Rust/Cargo not found. Please install Rust"
    exit 1
fi

echo "✅ Rust found"

if [ -f "Cargo.toml" ]; then
    echo "📦 Building Rust project..."
    cargo build
fi

"""
    
    def _generate_go_setup(self, files):
        """Generate Go setup"""
        return """# Go Setup
if ! command -v go &> /dev/null; then
    echo "❌ Go not found. Please install Go 1.19+"
    exit 1
fi

echo "✅ Go found"

if [ -f "go.mod" ]; then
    echo "📦 Installing Go dependencies..."
    go mod tidy
fi

"""
    
    def _generate_generic_setup(self, files):
        """Generate generic setup for other languages"""
        return """# Generic Setup
echo "📁 Files extracted successfully"
echo "🔍 Please check individual files for specific setup instructions"

"""
    
    def _generate_run_instructions(self, files, main_language):
        """Generate run instructions based on main file"""
        main_files = [f for f in files if f['name'] in ['main.py', 'app.py', 'index.js', 'main.js', 'main.rs', 'main.go']]
        
        if not main_files:
            # Find likely main file
            main_files = [f for f in files if 'main' in f['name'].lower() or f['name'].startswith('app.')]
        
        if not main_files and files:
            main_files = [files[0]]  # Use first file as fallback
        
        instructions = """
echo "🚀 Setup complete!"
echo ""
echo "📋 To run your project:"
"""
        
        if main_files:
            main_file = main_files[0]['name']
            
            if main_language == 'python':
                instructions += f'echo "   python3 {main_file}"\n'
            elif main_language == 'javascript':
                instructions += f'echo "   node {main_file}"\n'
            elif main_language == 'rust':
                instructions += 'echo "   cargo run"\n'
            elif main_language == 'go':
                instructions += f'echo "   go run {main_file}"\n'
            else:
                instructions += f'echo "   Check {main_file} for instructions"\n'
        
        instructions += """echo ""
echo "🦚 Generated by Peacock - Happy coding!"
"""
        
        return instructions
    
    def create_download_package(self, llm_response, project_name="peacock_project"):
        """Create a complete download package"""
        # Extract files from LLM response
        files = self.extract_files_from_llm_response(llm_response)
        
        if not files:
            return None
        
        # Create temporary project directory
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        project_dir = self.temp_dir / f"{project_name}_{timestamp}"
        project_dir.mkdir(exist_ok=True)
        
        # Write all files
        for file_info in files:
            file_path = project_dir / file_info['name']
            file_path.parent.mkdir(parents=True, exist_ok=True)
            
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(file_info['content'])
        
        # Generate setup script
        setup_script = self.generate_setup_script(files, project_name)
        setup_path = project_dir / "setup.sh"
        with open(setup_path, 'w', encoding='utf-8') as f:
            f.write(setup_script)
        
        # Make setup script executable
        os.chmod(setup_path, 0o755)
        
        # Generate README
        readme_content = self._generate_readme(files, project_name)
        readme_path = project_dir / "README.md"
        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(readme_content)
        
        # Create zip file
        zip_path = self.temp_dir / f"{project_name}_{timestamp}.zip"
        with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for file_path in project_dir.rglob('*'):
                if file_path.is_file():
                    arcname = file_path.relative_to(project_dir)
                    zipf.write(file_path, arcname)
        
        # Clean up temp directory
        shutil.rmtree(project_dir)
        
        return {
            "zip_path": str(zip_path),
            "file_count": len(files),
            "project_name": project_name,
            "timestamp": timestamp,
            "main_language": self._detect_main_language(files),
            "framework": self._detect_framework(files)
        }
    
    def _generate_readme(self, files, project_name):
        """Generate README.md file"""
        main_language = self._detect_main_language(files)
        framework = self._detect_framework(files)
        
        readme = f"""# {project_name}

Generated by Peacock on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Project Info
- **Language**: {main_language.title()}
"""
        
        if framework:
            readme += f"- **Framework**: {framework.title()}\n"
        
        readme += f"- **Files**: {len(files)} files\n\n"
        
        readme += """## Quick Start

1. **Extract the project**:
   ```bash
   unzip your-project.zip
   cd your-project
   ```

2. **Run setup script**:
   ```bash
   chmod +x setup.sh
   ./setup.sh
   ```

3. **Follow the instructions** displayed by the setup script

## Files Included

"""
        
        for file_info in files:
            readme += f"- `{file_info['name']}` - {file_info['language'].title()}\n"
        
        readme += """
## Manual Setup

If the setup script doesn't work, you can set up manually:

"""
        
        if main_language == 'python':
            readme += """### Python
```bash
# Install Python 3.8+
python3 -m pip install -r requirements.txt  # if requirements.txt exists
python3 main.py  # or your main file
```
"""
        elif main_language == 'javascript':
            readme += """### Node.js
```bash
# Install Node.js 16+
npm install  # if package.json exists
node main.js  # or your main file
```
"""
        elif main_language == 'rust':
            readme += """### Rust
```bash
# Install Rust
cargo build
cargo run
```
"""
        elif main_language == 'go':
            readme += """### Go
```bash
# Install Go 1.19+
go mod tidy  # if go.mod exists
go run main.go  # or your main file
```
"""
        
        readme += """
## Support

This project was generated by Peacock. For issues:
1. Check the setup script output
2. Verify all dependencies are installed
3. Check individual file comments for specific instructions

Happy coding! 🦚
"""
        
        return readme

if __name__ == "__main__":
    # Test the download manager
    manager = PeacockDownloadManager()
    
    sample_response = '''Here's a simple calculator:

```filename: calculator.py
def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def main():
    print("Simple Calculator")
    print("1 + 2 =", add(1, 2))
    print("5 - 3 =", subtract(5, 3))

if __name__ == "__main__":
    main()
```

```filename: requirements.txt
# No external dependencies needed
```
'''
    
    result = manager.create_download_package(sample_response, "test_calculator")
    if result:
        print(f"✅ Package created: {result['zip_path']}")
        print(f"📁 Files: {result['file_count']}")
        print(f"🔤 Language: {result['main_language']}")
    else:
        print("❌ Failed to create package")